### ISSUE TITLE
哇！ 老学长来问下 这是哪门课呀～

### ISSUE THREAD

**Issue by wfnuser** [El-even-11/SimpleDB#1]
感觉超级厉害 现在学弟们在读期间已经都可以写数据库了吗！ 羡慕羡慕
要不要来我们公司实习一波 哈哈哈 www.github.com/emqx

**Comment by El-even-11** [comment]
学长好！这门课是 [MIT6.830](http://db.lcs.mit.edu/6.830/index.php)
我是2020级，开学大二。做这个项目是想锻炼java的工程能力，然后稍微了解数据库基础知识，只是刚刚入门的水平（躺
我也非常希望能够尽早实习，然而目前知识能力尚且不足，并且课程比较紧张，所以暂时无法参加实习
但我想了解学长公司对实习生能力、技术栈的要求，我可以朝这个方向努力哈哈哈
感谢学长关心！祝好

**Comment by wfnuser** [comment]
> 学长好！这门课是 [MIT6.830](http://db.lcs.mit.edu/6.830/index.php)
> 我是2020级，开学大二。做这个项目是想锻炼java的工程能力，然后稍微了解数据库基础知识，只是刚刚入门的水平（躺
> 我也非常希望能够尽早实习，然而目前知识能力尚且不足，并且课程比较紧张，所以暂时无法参加实习
> 但我想了解学长公司对实习生能力、技术栈的要求，我可以朝这个方向努力哈哈哈
> 感谢学长关心！祝好

好呀 我是不是有加你微信哦 我们公司可以远程实习的。 公司做的方向非常多，主要围绕网络、存储、分布式、函数式编程。
如果你有时间的话，非常推荐你学习一下haskell以及函数式编程相关的东西（好像学校现在已经开了相关的课程可以去选修一下）。 类型理论、范畴论、计算机语言本身都是计算机世界里非常富有美感和集结先辈智慧的学科。不要都被卷到机器学习的坑里了，大部分工作其实是非常boring的，而且到工业界之后会发现非常浮躁，技术普遍也比较拉垮，当然你要都了解一下再做出自己的判断。我的看法可能也是偏激而片面的。

那期待等你大二暑假空一些的时候来我们公司实习哦！ 可以加我微信 wfnusee 交流。 相信你们以后都很厉害，我在大二的时候还总想着创业和一些其他乱七八糟的事情，现在非常后悔。 等你发现了计算机世界的美妙之后，有机会去读个PhD，为探索人类智力边界做贡献是非常好的。

选择了交大就是选择了责任。加油！

**Comment by wfnuser** [comment]
语言上 推荐多学 C++ rust haskell
Java不得不说 不算是一个对提高计算机基础知识理解的最佳选择
